# Since this is an portfolio project, just build all as a latest image

name: Build

on:
  push:
    branches: 
      - develop
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Dockerfile
          push: true
          tags: rlatmdxo50/work-unity-server:latest

  trigger-deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - 
        name: Trigger Deployment
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.PAT }}
          repository: rlatmdxo50/work-unity
          event-type: deploy-event